"""add Department

Revision ID: 207541cee453
Revises: 40fc0d58ce1b
Create Date: 2024-05-13 11:18:57.501820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207541cee453'
down_revision = '40fc0d58ce1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
