"""rename address

Revision ID: 2fab27a4606a
Revises: 990a6891d0cb
Create Date: 2024-05-13 11:28:47.691640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fab27a4606a'
down_revision = '990a6891d0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')  
    # ### end Alembic commands ###
